{% set name = "trident-chemwidgets" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trident_chemwidgets-{{ version }}.tar.gz
  sha256: 6ed98abe25a7601070c47ef6f959c74cc0604f661ec5bf03208cccc31c04b923

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipywidgets >=7.0.0
    - pandas >=1.0.0
    - python >=3.6

test:
  imports:
    - trident_chemwidgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tridentbio/trident-chemwidgets
  summary: Jupyter widgets for working with chemical datasets
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - TShimko126
